import streamlit as st
import yfinance as yf
import pandas as pd
import pandas_ta as ta
import numpy as np
import plotly.graph_objects as go
from plotly.subplots import make_subplots
from datetime import date, timedelta

st.set_page_config(page_title="Market Summary", layout="wide")

currency = "₹"
ticker_symbol = st.session_state.get('ticker_symbol', 'RELIANCE.NS')
selected_company = st.session_state.get('selected_company', 'Reliance Industries')

end_date = date.today()
start_date = end_date - timedelta(days=365)

# UI Layout
col_chart, col_tools = st.columns([8, 2])

with col_tools:
    st.subheader("Chart Tools")
    timeframe = st.selectbox("Timeframe", ["1d", "1wk", "1mo"], index=0)
    
    st.write("**Technical Overlays**")
    show_support_res = st.checkbox("Support & Resistance (20d)", value=True)
    show_trend = st.checkbox("EMA Trend (9/21)", value=True)
    show_doji = st.checkbox("Detect Doji Patterns", value=True)

with col_chart:
    st.markdown(f"### {selected_company} Advanced Terminal")
    
    # Fetch Data
    df = yf.download(ticker_symbol, start=start_date, end=end_date, interval=timeframe)
    if isinstance(df.columns, pd.MultiIndex):
        df.columns = df.columns.get_level_values(0)
    df.ffill(inplace=True)
    
    if len(df) > 20:
        # Technical Analysis using pandas_ta
        if show_support_res:
            df['Support'] = df['Low'].rolling(window=20).min()
            df['Resistance'] = df['High'].rolling(window=20).max()
            
        if show_trend:
            df.ta.ema(length=9, append=True)
            df.ta.ema(length=21, append=True)
            
        if show_doji:
            df.ta.cdl_pattern(name="doji", append=True)
            # Find the exact column name generated by pandas_ta
            doji_col = [col for col in df.columns if 'DOJI' in col]

        # Build Subplots (Price on top, Volume on bottom)
        fig = make_subplots(rows=2, cols=1, shared_xaxes=True, vertical_spacing=0.03, row_heights=[0.8, 0.2])

        # 1. Candlestick Chart
        fig.add_trace(go.Candlestick(
            x=df.index, open=df['Open'].squeeze(), high=df['High'].squeeze(), 
            low=df['Low'].squeeze(), close=df['Close'].squeeze(), name="Price",
            increasing_line_color='#089981', decreasing_line_color='#F23645'
        ), row=1, col=1)

        # 2. Overlays
        if show_support_res:
            fig.add_trace(go.Scatter(x=df.index, y=df['Support'], mode='lines', line=dict(color='green', dash='dot'), name='Support'), row=1, col=1)
            fig.add_trace(go.Scatter(x=df.index, y=df['Resistance'], mode='lines', line=dict(color='red', dash='dot'), name='Resistance'), row=1, col=1)

        if show_trend:
            fig.add_trace(go.Scatter(x=df.index, y=df['EMA_9'], mode='lines', line=dict(color='blue', width=1.5), name='EMA 9'), row=1, col=1)
            fig.add_trace(go.Scatter(x=df.index, y=df['EMA_21'], mode='lines', line=dict(color='orange', width=1.5), name='EMA 21'), row=1, col=1)

        # 3. Doji Pattern Markers
        if show_doji and doji_col:
            doji_days = df[df[doji_col[0]] != 0]
            if not doji_days.empty:
                fig.add_trace(go.Scatter(
                    x=doji_days.index, y=doji_days['High'] + (doji_days['High']*0.01),
                    mode='markers', marker=dict(symbol='triangle-down', size=10, color='yellow'),
                    name='Doji Pattern'
                ), row=1, col=1)

        # 4. Volume (Color-coded)
        vol_colors = ['#089981' if df['Close'].iloc[i] >= df['Open'].iloc[i] else '#F23645' for i in range(len(df))]
        fig.add_trace(go.Bar(x=df.index, y=df['Volume'].squeeze(), marker_color=vol_colors, name="Volume"), row=2, col=1)

        # Layout
        fig.update_layout(height=700, margin=dict(l=0, r=0, t=10, b=0), template="plotly_dark", xaxis_rangeslider_visible=False)
        if timeframe == "1d":
            fig.update_xaxes(rangebreaks=[dict(bounds=["sat", "mon"])])
            
        st.plotly_chart(fig, use_container_width=True)